module.exports = [
    {name: 'Alabama', code: 'AL', 'country_id': 1},
    {name: 'Alaska', code: 'AK', 'country_id': 1},
    {name: 'Arizona', code: 'AZ', 'country_id': 1},
    {name: 'Arkansas', code: 'AR', 'country_id': 1},
    {name: 'California', code: 'CA', 'country_id': 1},
    {name: 'Colorado', code: 'CO', 'country_id': 1},
    {name: 'Connecticut', code: 'CT', 'country_id': 1},
    {name: 'Delaware', code: 'DE', 'country_id': 1},
    {name: 'Florida', code: 'FL', 'country_id': 1},
    {name: 'Georgia', code: 'GA', 'country_id': 1},
    {name: 'Hawaii', code: 'HI', 'country_id': 1},
    {name: 'Idaho', code: 'ID', 'country_id': 1},
    {name: 'Illinois', code: 'IL', 'country_id': 1},
    {name: 'Indiana', code: 'IN', 'country_id': 1},
    {name: 'Iowa', code: 'IA', 'country_id': 1},
    {name: 'Kansas', code: 'KS', 'country_id': 1},
    {name: 'Kentucky', code: 'KY', 'country_id': 1},
    {name: 'Louisiana', code: 'LA', 'country_id': 1},
    {name: 'Maine', code: 'ME', 'country_id': 1},
    {name: 'Maryland', code: 'MD', 'country_id': 1},
    {name: 'Massachusetts', code: 'MA', 'country_id': 1},
    {name: 'Michigan', code: 'MI', 'country_id': 1},
    {name: 'Minnesota', code: 'MN', 'country_id': 1},
    {name: 'Mississippi', code: 'MS', 'country_id': 1},
    {name: 'Missouri', code: 'MO', 'country_id': 1},
    {name: 'Montana', code: 'MT', 'country_id': 1},
    {name: 'Nebraska', code: 'NE', 'country_id': 1},
    {name: 'Nevada', code: 'NV', 'country_id': 1},
    {name: 'New Hampshire', code: 'NH', 'country_id': 1},
    {name: 'New Jersey', code: 'NJ', 'country_id': 1},
    {name: 'New Mexico', code: 'NM', 'country_id': 1},
    {name: 'New York', code: 'NY', 'country_id': 1},
    {name: 'North Carolina', code: 'NC', 'country_id': 1},
    {name: 'North Dakota', code: 'ND', 'country_id': 1},
    {name: 'Ohio', code: 'OH', 'country_id': 1},
    {name: 'Oklahoma', code: 'OK', 'country_id': 1},
    {name: 'Oregon', code: 'OR', 'country_id': 1},
    {name: 'Pennsylvania', code: 'PA', 'country_id': 1},
    {name: 'Rhode Island', code: 'RI', 'country_id': 1},
    {name: 'South Carolina', code: 'SC', 'country_id': 1},
    {name: 'South Dakota', code: 'SD', 'country_id': 1},
    {name: 'Tennessee', code: 'TN', 'country_id': 1},
    {name: 'Texas', code: 'TX', 'country_id': 1},
    {name: 'Utah', code: 'UT', 'country_id': 1},
    {name: 'Vermont', code: 'VT', 'country_id': 1},
    {name: 'Virginia', code: 'VA', 'country_id': 1},
    {name: 'Washington', code: 'WA', 'country_id': 1},
    {name: 'West Virginia', code: 'WV', 'country_id': 1},
    {name: 'Wisconsin', code: 'WI', 'country_id': 1},
    {name: 'Wyoming', code: 'WY', 'country_id': 1},
    {name: 'Alborz', code: 'ALB', 'country_id': 2},
    {name: 'Ardabil', code: 'ARD', 'country_id': 2},
    {name: 'Azerbaijan, East', code: 'AZE', 'country_id': 2},
    {name: 'Azerbaijan, West', code: 'AZW', 'country_id': 2},
    {name: 'Bushehr', code: 'BUS', 'country_id': 2},
    {name: 'Chahar Mahaal and Bakhtiari', code: 'CMB', 'country_id': 2},
    {name: 'Fars', code: 'FAR', 'country_id': 2},
    {name: 'Gilan', code: 'GIL', 'country_id': 2},
    {name: 'Golestan', code: 'GOL', 'country_id': 2},
    {name: 'Hamadan', code: 'HAM', 'country_id': 2},
    {name: 'Hormozgan', code: 'HOR', 'country_id': 2},
    {name: 'Ilam', code: 'ILA', 'country_id': 2},
    {name: 'Isfahan', code: 'ISF', 'country_id': 2},
    {name: 'Kerman', code: 'KER', 'country_id': 2},
    {name: 'Kermanshah', code: 'KSH', 'country_id': 2},
    {name: 'Khorasan, North', code: 'KHN', 'country_id': 2},
    {name: 'Khorasan, Razavi', code: 'KHR', 'country_id': 2},
    {name: 'Khorasan, South', code: 'KHS', 'country_id': 2},
    {name: 'Khuzestan', code: 'KHU', 'country_id': 2},
    {name: 'Kohgiluyeh and Boyer-Ahmad', code: 'KBA', 'country_id': 2},
    {name: 'Kurdistan', code: 'KUD', 'country_id': 2},
    {name: 'Lorestan', code: 'LOR', 'country_id': 2},
    {name: 'Markazi', code: 'MAR', 'country_id': 2},
    {name: 'Mazandaran', code: 'MAZ', 'country_id': 2},
    {name: 'Qazvin', code: 'QAZ', 'country_id': 2},
    {name: 'Qom', code: 'QOM', 'country_id': 2},
    {name: 'Sistan and Baluchestan', code: 'SBA', 'country_id': 2},
    {name: 'Tehran', code: 'TEH', 'country_id': 2},
    {name: 'Yazd', code: 'YAZ', 'country_id': 2},
    {name: 'Zanjan', code: 'ZAN', 'country_id': 2}
  ];